const Footer = () => {
  return (
    <div className="f-container">
      <div className="scroll-right">
        <p>
          “EXECUTIVE” “CREATIVE” “DIRECTION” “EXECUTIVE” “CREATIVE” “DIRECTION"
          “EXECUTIVE” “CREATIVE” “DIRECTION” “EXECUTIVE” “CREATIVE” “DIRECTION"
          “EXECUTIVE” “CREATIVE” “DIRECTION” “EXECUTIVE” “CREATIVE” “DIRECTION"
          “EXECUTIVE” “CREATIVE” “DIRECTION” “EXECUTIVE” “CREATIVE” “DIRECTION"
          “EXECUTIVE” “CREATIVE” “DIRECTION” “EXECUTIVE” “CREATIVE” “DIRECTION"
          “EXECUTIVE” “CREATIVE” “DIRECTION” “EXECUTIVE” “CREATIVE” “DIRECTION"
          “EXECUTIVE” “CREATIVE” “DIRECTION” “EXECUTIVE” “CREATIVE” “DIRECTION"
          “EXECUTIVE” “CREATIVE” “DIRECTION” “EXECUTIVE” “CREATIVE” “DIRECTION"
          “EXECUTIVE” “CREATIVE” “DIRECTION” “EXECUTIVE” “CREATIVE”
          “DIRECTION"“EXECUTIVE” “CREATIVE” “DIRECTION” “EXECUTIVE” “CREATIVE”
          “DIRECTION" “EXECUTIVE” “CREATIVE” “DIRECTION" “EXECUTIVE” “CREATIVE”
          “DIRECTION" “EXECUTIVE” “CREATIVE” “DIRECTION" “EXECUTIVE” “CREATIVE”
          “DIRECTION" “EXECUTIVE” “CREATIVE” “DIRECTION" “EXECUTIVE” “CREATIVE”
          “DIRECTION" “EXECUTIVE” “CREATIVE” “DIRECTION" “EXECUTIVE” “CREATIVE”
          “DIRECTION" “EXECUTIVE” “CREATIVE” “DIRECTION" “EXECUTIVE” “CREATIVE”
          “DIRECTION" “EXECUTIVE” “CREATIVE” “DIRECTION" “EXECUTIVE” “CREATIVE”
          “DIRECTION" “EXECUTIVE” “CREATIVE” “DIRECTION" “EXECUTIVE” “CREATIVE”
          “DIRECTION" “EXECUTIVE” “CREATIVE” “DIRECTION" “EXECUTIVE” “CREATIVE”
          “DIRECTION" “EXECUTIVE” “CREATIVE” “DIRECTION" “EXECUTIVE” “CREATIVE”
          “DIRECTION" “EXECUTIVE” “CREATIVE” “DIRECTION" “EXECUTIVE” “CREATIVE”
          “DIRECTION"
        </p>
      </div>
    </div>
  );
};

export default Footer;
